# Generated by Django 6.1 on 2026-09-14 22:50

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('color', models.CharField(max_length=80)),
                ('tipo', models.CharField(choices=[('camisa', 'Camisa'), ('pantalon', 'Pantalón'), ('zapatos', 'Zapatos'), ('polera', 'Polera'), ('chaqueta', 'Chaqueta'), ('otro', 'Otro')], max_length=15)),
                ('estado', models.CharField(choices=[('limpio', 'Limpio'), ('sucio', 'Sucio'), ('planchado', 'Planchado')], max_length=12)),
                ('formalidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('resultado_decision', models.CharField(max_length=255)),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now)),
                ('eliminado', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.DeleteModel(
            name='Registro',
        ),
    ]
